global_frame: odom
rolling_window: true

inflation:
    inflation_radius: 3.0
    
plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
